version: '3.6'

services:
  #Backend API
  facerecognition-api:
    container_name: backend
    build: .
    command: npm start
    working_dir: /usr/src/facerecognition-api
    environment:
      POSTGRES_USER: evil
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: facerecognition-docker
      POSTGRES_HOST: postgres
    links:
      - postgres
    ports:
      - "3000:3000"
    volumes:
        - ./:/usr/src/facerecognition-api

  #postgres
  postgres:
    environment:
      POSTGRES_USER: evil
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: facerecognition-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    restart: always
    # volumes:
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5555:5555"
